### ISSUE TITLE
subscribe无法收到服务全部下线

### ISSUE THREAD

**Issue by mingxinkejian** [opc-source/nacos-sdk-rust-binding-node#24]
例如
当前有1个服务，该服务下有N个服务器列表。依次下线时，监听回调只能收到前2个服务服务器下线的通知，当第三个服务器下线后，因为服务器全部下线，服务列表已经是空的了，此时不会回调服务监听。

**Comment by CherishCai** [comment]
嗯，确实内置了防推空逻辑，应该提供一个环境变量让用户设置该逻辑开关。

请问你是什么情况下去要获取到空列表呢？

**Comment by mingxinkejian** [comment]
> 嗯，确实内置了防推空逻辑，应该提供一个环境变量让用户设置该逻辑开关。
> 
> 请问你是什么情况下去要获取到空列表呢？

需要清理内存里的数据呀，否则的话业务层保存的服务器信息始终会保留呀。这个和Java的ClientSDK提供的逻辑不一样啊~~

**Comment by CherishCai** [comment]
> 需要清理内存里的数据呀，否则的话业务层保存的服务器信息始终会保留呀。这个和Java的ClientSDK提供的逻辑不一样啊~~

@mingxinkejian  确实是有不一样，nacos-client java 默认防推空为 false。之前我这边都给设置成 true ，大多数情况下还没发现需要 false 的。所以实现 rust 版客户端的时候就默认 true 了

**Comment by mingxinkejian** [comment]
> > 需要清理内存里的数据呀，否则的话业务层保存的服务器信息始终会保留呀。这个和Java的ClientSDK提供的逻辑不一样啊~~
> 
> @mingxinkejian 确实是有不一样，nacos-client java 默认防推空为 false。之前我这边都给设置成 true ，大多数情况下还没发现需要 false 的。所以实现 rust 版客户端的时候就默认 true 了

感谢大佬，可以加一个设置来控制这个空推。

**Comment by CherishCai** [comment]
请尝试 0.3.2 可以在参数设置，也可以环境变量
