### ISSUE TITLE
在Linux环境下，如果用户根目录/xxx/nacos/xxx@@xxx@@xxx

### ISSUE THREAD

**Issue by mingxinkejian** [opc-source/nacos-sdk-rust-binding-node#25]
大佬，咨询个问题，在linux或者windows下，用户目录中的/root/nacos/xxx@@xxx文件如果存在的话，在服务不变的情况下，客户端重启是不会回调listener来触发注册通知的。
这个会导致，重启后的客户端收不到注册通知，而无法维护服务注册。不知道是不是bug？
如果我每次重启的时候，把这个文件先删除，后启动的话，就会重新触发注册通知。

**Comment by CherishCai** [comment]
年后再看哈。
node 这边只是个简单的绑定，年后看看 rust 那边是否没处理好本地文件缓存的逻辑

**Comment by CherishCai** [comment]
@onewe 看代码好像确有其事？求协助

**Comment by mingxinkejian** [comment]
大佬，啥时候能修复呀~~

**Comment by CherishCai** [comment]
我去看看 Java 如何实现的～

默认 namingLoadCacheAtStart=false
![image](https://github.com/opc-source/nacos-sdk-rust-binding-node/assets/16837364/c68fdba0-f20c-4c3f-b994-0bff6219dc27)

**Comment by CherishCai** [comment]
我来修改一下 rust 那边发个版本再来更新 binding-node

**Comment by CherishCai** [comment]
@mingxinkejian 试一下 0.3.5

**Comment by mingxinkejian** [comment]
嗯，貌似好了^_^
